structure(list(method = "POST", url = "https://api.deepseek.com/chat/completions", 
    status_code = 200L, headers = structure(list(date = "Thu, 20 Mar 2025 09:10:26 GMT", 
        `content-type` = "application/json", `set-cookie` = "REDACTED", 
        vary = "origin, access-control-request-method, access-control-request-headers", 
        vary = "accept-encoding", `access-control-allow-credentials` = "true", 
        `x-ds-trace-id` = "371143f685ece93aa47bea09968948fb", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `x-content-type-options` = "nosniff", `content-encoding` = "gzip", 
        `cf-cache-status` = "DYNAMIC", `set-cookie` = "REDACTED", 
        `set-cookie` = "REDACTED", server = "cloudflare", `cf-ray` = "9234138b5e7b2c09-STR"), class = "httr2_headers"), 
    body = charToRaw("{\"id\":\"a1238c82-7ab8-4d74-b3b1-44bb1ed446bd\",\"object\":\"chat.completion\",\"created\":1742461825,\"model\":\"deepseek-chat\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"Hello, world! How can I assist you today? 😊\"},\"logprobs\":null,\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":13,\"completion_tokens\":13,\"total_tokens\":26,\"prompt_tokens_details\":{\"cached_tokens\":0},\"prompt_cache_hit_tokens\":0,\"prompt_cache_miss_tokens\":13},\"system_fingerprint\":\"fp_3a5770e1b4_prod0225\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
