structure(list(method = "POST", url = "https://api.openai.com/v1/chat/completions", 
    status_code = 200L, headers = structure(list(date = "Mon, 18 Nov 2024 13:04:34 GMT", 
        `content-type` = "application/json", `access-control-expose-headers` = "X-Request-ID", 
        `openai-organization` = "user-fqp2dkp45jw9evqyihjoiujj", 
        `openai-processing-ms` = "406", `openai-version` = "2020-10-01", 
        `x-ratelimit-limit-requests` = "500", `x-ratelimit-limit-tokens` = "30000", 
        `x-ratelimit-remaining-requests` = "499", `x-ratelimit-remaining-tokens` = "29961", 
        `x-ratelimit-reset-requests` = "120ms", `x-ratelimit-reset-tokens` = "78ms", 
        `x-request-id` = "req_813402cb6c97c417254b517a1740b8b4", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `cf-cache-status` = "DYNAMIC", `set-cookie` = "REDACTED", 
        `x-content-type-options` = "nosniff", `set-cookie` = "REDACTED", 
        server = "cloudflare", `cf-ray` = "8e482ac6c9380fcc-LAX", 
        `content-encoding` = "gzip", `alt-svc` = "h3=\":443\"; ma=86400"), class = "httr2_headers"), 
    body = charToRaw("{\n  \"id\": \"chatcmpl-AUvic60PogiQAGGWLYLnKOL1N2Kh3\",\n  \"object\": \"chat.completion\",\n  \"created\": 1731935074,\n  \"model\": \"gpt-4o-2024-08-06\",\n  \"choices\": [\n    {\n      \"index\": 0,\n      \"message\": {\n        \"role\": \"assistant\",\n        \"content\": \"{\\\"area\\\":150.5}\",\n        \"refusal\": null\n      },\n      \"logprobs\": null,\n      \"finish_reason\": \"stop\"\n    }\n  ],\n  \"usage\": {\n    \"prompt_tokens\": 55,\n    \"completion_tokens\": 7,\n    \"total_tokens\": 62,\n    \"prompt_tokens_details\": {\n      \"cached_tokens\": 0,\n      \"audio_tokens\": 0\n    },\n    \"completion_tokens_details\": {\n      \"reasoning_tokens\": 0,\n      \"audio_tokens\": 0,\n      \"accepted_prediction_tokens\": 0,\n      \"rejected_prediction_tokens\": 0\n    }\n  },\n  \"system_fingerprint\": \"fp_45c6de4934\"\n}\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
