structure(list(method = "POST", url = "https://api.openai.com/v1/chat/completions", 
    status_code = 200L, headers = structure(list(date = "Mon, 18 Nov 2024 13:04:49 GMT", 
        `content-type` = "application/json", `access-control-expose-headers` = "X-Request-ID", 
        `openai-organization` = "user-fqp2dkp45jw9evqyihjoiujj", 
        `openai-processing-ms` = "444", `openai-version` = "2020-10-01", 
        `x-ratelimit-limit-requests` = "500", `x-ratelimit-limit-tokens` = "30000", 
        `x-ratelimit-remaining-requests` = "499", `x-ratelimit-remaining-tokens` = "29957", 
        `x-ratelimit-reset-requests` = "120ms", `x-ratelimit-reset-tokens` = "86ms", 
        `x-request-id` = "req_d1a62788c30c40012cc2a2e9fc5cebdb", 
        `strict-transport-security` = "max-age=31536000; includeSubDomains; preload", 
        `cf-cache-status` = "DYNAMIC", `set-cookie` = "REDACTED", 
        `x-content-type-options` = "nosniff", `set-cookie` = "REDACTED", 
        server = "cloudflare", `cf-ray` = "8e482b228cc80fcc-LAX", 
        `content-encoding` = "gzip", `alt-svc` = "h3=\":443\"; ma=86400"), class = "httr2_headers"), 
    body = charToRaw("{\n  \"id\": \"chatcmpl-AUvirNsmah46RGshd8qmuxMzVesfr\",\n  \"object\": \"chat.completion\",\n  \"created\": 1731935089,\n  \"model\": \"gpt-4o-2024-08-06\",\n  \"choices\": [\n    {\n      \"index\": 0,\n      \"message\": {\n        \"role\": \"assistant\",\n        \"content\": \"{\\\"area\\\":250.5,\\\"population\\\":150000}\",\n        \"refusal\": null\n      },\n      \"logprobs\": null,\n      \"finish_reason\": \"stop\"\n    }\n  ],\n  \"usage\": {\n    \"prompt_tokens\": 64,\n    \"completion_tokens\": 12,\n    \"total_tokens\": 76,\n    \"prompt_tokens_details\": {\n      \"cached_tokens\": 0,\n      \"audio_tokens\": 0\n    },\n    \"completion_tokens_details\": {\n      \"reasoning_tokens\": 0,\n      \"audio_tokens\": 0,\n      \"accepted_prediction_tokens\": 0,\n      \"rejected_prediction_tokens\": 0\n    }\n  },\n  \"system_fingerprint\": \"fp_159d8341cc\"\n}\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
