structure(list(method = "POST", url = "https://api.mistral.ai/v1/chat/completions", 
    status_code = 200L, headers = structure(list(date = "Thu, 20 Mar 2025 08:03:37 GMT", 
        `content-type` = "application/json", `ratelimitbysize-query-cost` = "1027", 
        `x-ratelimitbysize-limit-minute` = "2000000", `x-ratelimitbysize-remaining-minute` = "1998973", 
        `ratelimitbysize-remaining` = "1998973", `ratelimitbysize-limit` = "2000000", 
        `ratelimitbysize-reset` = "24", `x-ratelimitbysize-limit-month` = "10000000000", 
        `x-ratelimitbysize-remaining-month` = "9999998973", `x-envoy-upstream-service-time` = "559", 
        `access-control-allow-origin` = "*", `x-kong-upstream-latency` = "559", 
        `x-kong-proxy-latency` = "1", `x-kong-request-id` = "ffe9260980e6fc3940a3d56bf49cf176", 
        `cf-cache-status` = "DYNAMIC", `set-cookie` = "REDACTED", 
        server = "cloudflare", `cf-ray` = "9233b1aabb334d6a-FRA", 
        `content-encoding` = "gzip", `alt-svc` = "h3=\":443\"; ma=86400"), class = "httr2_headers"), 
    body = charToRaw("{\"id\":\"77e23ffbc1eb431891c703995e040a98\",\"object\":\"chat.completion\",\"created\":1742457816,\"model\":\"mistral-large-latest\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"tool_calls\":null,\"content\":\"Hello! How can I assist you today? Let's have a friendly conversation.  How are you doing?\"},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":6,\"total_tokens\":29,\"completion_tokens\":23}}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
