structure(list(method = "POST", url = "https://api.mistral.ai/v1/chat/completions", 
    status_code = 200L, headers = structure(list(date = "Fri, 25 Oct 2024 16:27:41 GMT", 
        `content-type` = "application/json", `x-ratelimitbysize-remaining-day` = "149994462", 
        `x-ratelimitbysize-limit-day` = "150000000", `ratelimitbysize-query-cost` = "1027", 
        `ratelimitbysize-limit` = "500000", `ratelimitbysize-remaining` = "498973", 
        `x-ratelimitbysize-limit-minute` = "500000", `ratelimitbysize-reset` = "22", 
        `x-ratelimitbysize-remaining-minute` = "498973", `x-envoy-upstream-service-time` = "2975", 
        `access-control-allow-origin` = "*", `x-kong-upstream-latency` = "2976", 
        `x-kong-proxy-latency` = "2", `x-kong-request-id` = "56f7ba70eef4c3308cf99f5239a3e733", 
        `cf-cache-status` = "DYNAMIC", server = "cloudflare", 
        `cf-ray` = "8d83933adf2a8ec4-FRA", `content-encoding` = "gzip", 
        `alt-svc` = "h3=\":443\"; ma=86400"), class = "httr2_headers"), 
    body = charToRaw("{\"id\":\"11b89cadd3b640faac0ed20fcf33e618\",\"object\":\"chat.completion\",\"created\":1729873660,\"model\":\"mistral-large-latest\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"Hello! How can I assist you today? Let's chat about anything you'd like. 😊\",\"tool_calls\":null},\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":6,\"total_tokens\":28,\"completion_tokens\":22}}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
